Repository codu-code/codu, pull requests merged in 2022-10, with the labels that each got.

#57 Add code of conduct
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#60 Update workflow in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#92 feat: Use @vercel/og for dynamic OG image generation
  package-lock.json
  package.json
  pages/api/og.jsx
  pages/articles/[slug].tsx
Labels: hacktoberfest-accepted, hacktoberfest

#93 feat: Shuffle env to use example suffix and update README
  .env.example
  .gitignore
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#95 Fetches host URL from ServerSideProps
  components/Meta/Meta.tsx
  package-lock.json
  pages/articles/[slug].tsx
Labels: hacktoberfest
